// Generates the Nextra `content/` directory from the source notes.
//
// Source of truth = the top-level "Chapter N" folders (edited in Obsidian).
// This script copies each chapter's notes into `content/chapter-N.mdx` with a
// title, and regenerates `content/_meta.js` for the sidebar order.
//
// It runs automatically before every build (see the "prebuild" npm script),
// including on Vercel, so the deployed site always matches the notes.
//
// To add a chapter: create a "Chapter N" folder with a single `.md` file, and
// (optionally) add its subtitle to CHAPTER_TITLES below for a nicer label.

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const CONTENT_DIR = join(ROOT, 'content')

// Nice subtitles per chapter number. Missing entries fall back to "Chapter N".
const CHAPTER_TITLES = {
  1: 'Building Blocks',
  2: 'Operators'
}

// Discover "Chapter N" folders (each holding one Markdown file).
const chapters = readdirSync(ROOT)
  .map(name => {
    const m = /^Chapter (\d+)$/.exec(name)
    if (!m) return null
    const dir = join(ROOT, name)
    if (!statSync(dir).isDirectory()) return null
    const md = readdirSync(dir).find(f => f.toLowerCase().endsWith('.md'))
    if (!md) return null
    return { num: Number(m[1]), name, mdPath: join(dir, md) }
  })
  .filter(Boolean)
  .sort((a, b) => a.num - b.num)

if (chapters.length === 0) {
  console.warn('[build-content] No "Chapter N" folders found — nothing to generate.')
}

const meta = { index: { title: 'Home', theme: { breadcrumb: false, toc: false } } }

for (const ch of chapters) {
  const subtitle = CHAPTER_TITLES[ch.num]
  const title = subtitle ? `Chapter ${ch.num} — ${subtitle}` : `Chapter ${ch.num}`
  const slug = `chapter-${ch.num}`
  const body = readFileSync(ch.mdPath, 'utf8')
  const out = `---\ntitle: ${title}\n---\n\n${body}`
  writeFileSync(join(CONTENT_DIR, `${slug}.mdx`), out)
  meta[slug] = title
  console.log(`[build-content] ${ch.name} -> content/${slug}.mdx  ("${title}")`)
}

const metaOut =
  '// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.\n' +
  `export default ${JSON.stringify(meta, null, 2)}\n`
writeFileSync(join(CONTENT_DIR, '_meta.js'), metaOut)
console.log(`[build-content] Wrote content/_meta.js (${chapters.length} chapter(s)).`)
